"""empty message

Revision ID: 2b9edd7acc40
Revises: 13d761e99cf5
Create Date: 2014-10-04 09:51:33.114442

"""

# revision identifiers, used by Alembic.
revision = '2b9edd7acc40'
down_revision = '13d761e99cf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
